name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Copy files to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }}" \
            package.json package-lock.json server \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/backend

      - name: Install dependencies & Restart app
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd /var/www/backend &&
            npm install &&
            pm2 restart all || pm2 start server --name simplehh-backend
          "